<a href="https://colab.research.google.com/github/wlans01/2021_cphys2/blob/main/hw4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#XOR
- 하나의 히든 레이어를 도입한다.
- input layer는 2개의 노드 + 1개의 바이어스
- hidden layer는 3개의 노드 + 1개의 바이어스
- output은 하나의 노드로 한다.

In [1]:
X = np.array([[0,0,1],[1,0,1],[0,1,1],[1,1,1]]) #세번째 항은 bias
y = np.array([[0],[1],[1],[0]])

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
def f(x): 
    return 1/(1+np.exp(-x))

In [5]:
inputs, hiddens, outputs = 3,4,1
np.random.seed(1)
w = 2*np.random.random((inputs,hiddens))-1
omega = 2*np.random.random((hiddens,outputs))-1

In [6]:
dh=[0,0,0,0]
eta=1
for n in range(10000):
    E=0 # error_sum
    for i in range(4):
        neth=np.dot(X[i],w) 
        h = f(neth)
        neto=np.dot(h,omega) 
        o = f(neto)
        
        E = E + (o-y[i])**2
        do=(o-y[i])*f(neto)*(1-f(neto))
        for j in range(4):
            dh[j]=do*omega[j]*f(neth[j])*(1-f(neth[j]))
            omega[j]=omega[j]-eta*do*h[j]
            for k in range(3):
                w[k][j]=w[k][j]-eta*dh[j]*X[i][k]
E

array([0.00044546])

In [7]:
for i in range(4):
    neth=np.dot(X[i],w) 
    h = f(neth)
    neto=np.dot(h,omega)
    o = f(neto)
    print(o)

[0.00651827]
[0.9894139]
[0.99071994]
[0.01430354]


In [8]:
w,o

(array([[ 2.35603244,  4.41958143, -6.15235168, -6.33134315],
        [ 0.61286955, -6.82944491, -6.20002118,  2.86018093],
        [-1.11258573, -1.72172626,  2.08016084, -0.71621427]]),
 array([0.01430354]))